Config = {}

Config.Language = "English"

Config.DiscordWebhookLogNormal = "https://discord.com/api/webhooks/885373338824880138/b44ZB3v-KyzoXXiJOgaEIM0F52rrer_Ar1mzz4A9tjv_3du8viWBgN2zzFRg7mdmAEhv" --write here global anticheat webhook

Config.DiscordWebhookLogPhoto = "https://discord.com/api/webhooks/885373338824880138/b44ZB3v-KyzoXXiJOgaEIM0F52rrer_Ar1mzz4A9tjv_3du8viWBgN2zzFRg7mdmAEhv" --write here webhook for photo

Config.DiscordWebhookLogBan = "https://discord.com/api/webhooks/885373338824880138/b44ZB3v-KyzoXXiJOgaEIM0F52rrer_Ar1mzz4A9tjv_3du8viWBgN2zzFRg7mdmAEhv" --write here webhook for bans

Config.BanKickMessageUrl = "https://discord.gg/xxx" -- write here url of your discord server

Config.ServerName = "HYDRA" --write here server name 

Config.AntiCheatName = "💖 🛡️ HYDRA Anticheat 🛡️ 💖"

Config.BypassPerm = "rtxac.bypass"

Config.BanListPerm = "rtxac.banlist"

Config.AdminMenu = true

Config.AdminMenuCommand = "adminmenu"

Config.ScreenshotActions = true

Config.ESXServer = false

Config.ESXSharedObject = "esx:getSharedObject"

Config.AntiSpawnBlacklistedObjects = false

Config.AntiSpawnBlacklistedPeds = true

Config.AntiSpawnBlacklistedVehicles = true

Config.AntiSpawnMassObjects = false
Config.AntiSpawnMassObjectsMax = 30

Config.AntiSpawnMassPeds = false
Config.AntiSpawnMassPedsMax = 10

Config.AntiSpawnMassVehicles = false
Config.AntiSpawnMassVehiclesMax = 10

Config.AntiSpawnMassParticles = false
Config.AntiSpawnMassParticlesMax = 10

Config.WhitelistedObjectsOnly = false

Config.WhitelistedVehiclesOnly = false

Config.WhitelistedPedsOnly = false

Config.AntiVehicleRam = false

Config.AntiSuperJump = true

Config.DetectingTriggeringServerEvents = false

Config.AntiExplosionsDebuger = false

Config.BlockingBlacklistedMessages = true

Config.BlockingFakeMessages = true

Config.AntiBlacklistedPedChanger = true

Config.AntiBlacklistedWeaponUse = true

Config.AntiWeaponGive = true
Config.AntiWeaponGivePickupBypass = false -- activate if your server using weapon pickups

Config.AntiWeaponRemove = true

Config.AntiMaxHealtChanger = true

Config.SendingLogsToDiscord = true

Config.SendingBanLogsToDiscord = true

Config.AntiExplosions = true

Config.CheaterAnnounceForEveryone = true

Config.SuspiciousResourcesStop = true

Config.ModMenuChecking = false

Config.PedTaskCanceling = false --if true its blocking for example player kicking from vehicles

Config.PedTaskDetectingImmediately = false --to player

Config.PedTaskDetectingNormal = false --to player

Config.PedTaskDetectingToSomeone = false --to someone

Config.AntiBlacklistedPlayerNames = true

Config.GameTimerCheckingServer = 15000

Config.AntiAntiCheatStopCheckingServer = 10000

Config.EntityTablePlacerChecking = 5000

Config.PermissionChecking = 60000

Config.GlobalCheckingServer = 2000

Config.AntiVPN = false
Config.VPNBypassOnlyIP = true
Config.OnlySpecifiedCountries = true

Config.AntiBlipBypass = false
Config.AntiBlipBypassAce = false
Config.AntiBlipBypassJobs = false --for esx only
Config.AceBypassPerms = "rtxac.antiblipbypass"
Config.AntiBlipBypassJobs = { --for esx only
	{name = "police"},
	{name = "ambulance"},
	{name = "sheriff"},
}

Config.VPNBypassAdresses = { 
--	{playerip = "37.48.20.1024", playername = "Kanikuly", playersteam = "steam:11000013cc73739"},
}

Config.SpecifiedCountries = { 
	{country = "VN"},
}

Config.CheatsConfigure = { -- We recommend leaving the basic settings
	{typecheat = "spectating", ban = true, kick = true, info = true},
	{typecheat = "godmode", ban = true, kick = true, info = true},
	{typecheat = "maxarmor", ban = true, kick = true, info = true},	
	{typecheat = "blacklistedkeys", ban = false, kick = false, info = true},
	{typecheat = "cheatengine", ban = true, kick = true, info = true},
	{typecheat = "nrcmethod", ban = true, kick = true, info = true},
	{typecheat = "bcmethod", ban = true, kick = true, info = true},
	{typecheat = "screenresult", ban = true, kick = true, info = true},
	{typecheat = "injectioncommand", ban = true, kick = true, info = true},
	{typecheat = "blips", ban = true, kick = true, info = true},
	{typecheat = "antimodifer", ban = true, kick = true, info = true},
	{typecheat = "antidamagechange", ban = true, kick = true, info = true},
	{typecheat = "antiexplosivemelee", ban = false, kick = false, info = true},
	{typecheat = "antiexplosiveweapon", ban = true, kick = true, info = true},
	{typecheat = "speedhack", ban = false, kick = true, info = true},
	{typecheat = "noclip", ban = true, kick = true, info = true},
	{typecheat = "menucommandbl", ban = true, kick = true, info = true},
	{typecheat = "clienteventexecute", ban = true, kick = true, info = true},
	{typecheat = "gametime", ban = false, kick = true, info = true},
	{typecheat = "stopresource", ban = true, kick = true, info = true},
	{typecheat = "startresource", ban = true, kick = true, info = true},
	{typecheat = "startrandomstringresource", ban = true, kick = true, info = true},
	{typecheat = "maxhealth", ban = true, kick = true, info = true},
	{typecheat = "pedspawnblacklisted", ban = true, kick = true, info = true},
	{typecheat = "vehiclespawnblacklisted", ban = true, kick = true, info = true},	
	{typecheat = "objectspawnblacklisted", ban = true, kick = true, info = true},	
	{typecheat = "pedspawnmass", ban = true, kick = true, info = true},
	{typecheat = "vehiclespawnmass", ban = true, kick = true, info = true},	
	{typecheat = "objectspawnmass", ban = true, kick = true, info = true},		
	{typecheat = "servereventexecute", ban = true, kick = true, info = true},	
	{typecheat = "explosion", ban = true, kick = true, info = true},	
	{typecheat = "blacklistedchatmessage", ban = false, kick = true, info = true},	
	{typecheat = "fakechatmessage", ban = false, kick = true, info = true},
	{typecheat = "anticheatturnoff", ban = true, kick = true, info = true},	
	{typecheat = "superjump", ban = true, kick = true, info = true},	
	{typecheat = "dangerousvariables", ban = true, kick = true, info = true},	
	{typecheat = "injectedmenu", ban = true, kick = true, info = true},	
	{typecheat = "suspiciousresource", ban = true, kick = true, info = true},	
	{typecheat = "giveweapon", ban = true, kick = true, info = true},	
	{typecheat = "removeweapon", ban = true, kick = true, info = true},	
	{typecheat = "pedtask", ban = true, kick = true, info = true},	
	{typecheat = "teleport", ban = true, kick = true, info = true},	
	{typecheat = "invisible", ban = true, kick = true, info = true},	
	{typecheat = "spawnvehicle", ban = true, kick = true, info = true},	
	{typecheat = "nightvision", ban = true, kick = true, info = true},
	{typecheat = "thermalvision", ban = true, kick = true, info = true},	
	{typecheat = "vehicletuning", ban = true, kick = true, info = true},	
	{typecheat = "aimbot", ban = true, kick = true, info = true},	
	{typecheat = "esp", ban = true, kick = true, info = true},
	{typecheat = "whitelistedplatesspawnvehicle", ban = true, kick = true, info = true},
	{typecheat = "whitelistedspawnvehicle", ban = true, kick = true, info = true},
	{typecheat = "luafile", ban = true, kick = true, info = true},
	{typecheat = "infinityammo", ban = true, kick = true, info = true},
	{typecheat = "menyoo", ban = true, kick = true, info = true},
	{typecheat = "ragdoll", ban = true, kick = true, info = true},
	{typecheat = "radar", ban = true, kick = true, info = true},
	{typecheat = "blacklistedweaponuse", ban = false, kick = false, info = true},
	{typecheat = "blacklistedpeduse", ban = false, kick = false, info = true},
	{typecheat = "vehiclespeedmodifer", ban = true, kick = true, info = true},
	{typecheat = "particlesspawnmass", ban = true, kick = true, info = true},
	{typecheat = "nuidevtools", ban = true, kick = true, info = true},
	{typecheat = "licenseclear", ban = true, kick = true, info = true},
}

Config.Explosions = {
    [0] = { name = "Grenade", blacklisted = true, punish = true},
    [1] = { name = "GrenadeLauncher", blacklisted = true, punish = true},
    [2] = { name = "C4", blacklisted = true, punish = true},
    [3] = { name = "Molotov", blacklisted = true, punish = true},
    [4] = { name = "Rocket", blacklisted = true, punish = true},
    [5] = { name = "TankShell", blacklisted = true, punish = true},
    [6] = { name = "Hi_Octane", blacklisted = false, punish = false},
    [7] = { name = "Car", blacklisted = false, punish = false},
    [8] = { name = "Plance", blacklisted = false, punish = false},
    [9] = { name = "PetrolPump", blacklisted = false, punish = false},
    [10] = { name = "Bike", blacklisted = false, punish = false},
    [11] = { name = "Dir_Steam", blacklisted = false, punish = false},
    [12] = { name = "Dir_Flame", blacklisted = false, punish = false},
    [13] = { name = "Dir_Water_Hydrant", blacklisted = false, punish = false},
    [14] = { name = "Dir_Gas_Canister", blacklisted = false, punish = false},
    [15] = { name = "Boat", blacklisted = false, punish = false},
    [16] = { name = "Ship_Destroy", blacklisted = false, punish = false},
    [17] = { name = "Truck", blacklisted = false, punish = false},
    [18] = { name = "Bullet", blacklisted = false, punish = false},
    [19] = { name = "SmokeGrenadeLauncher", blacklisted = false, punish = false},
    [20] = { name = "SmokeGrenade", blacklisted = false, punish = false},
    [21] = { name = "BZGAS", blacklisted = false, punish = false},
    [22] = { name = "Flare", blacklisted = false, punish = false},
    [23] = { name = "Gas_Canister", blacklisted = false, punish = false},
    [24] = { name = "Extinguisher", blacklisted = false, punish = false},
    [25] = { name = "Programmablear", blacklisted = true, punish = false},
    [26] = { name = "Train", blacklisted = false, punish = false},
    [27] = { name = "Barrel", blacklisted = false, punish = false},
    [28] = { name = "PROPANE", blacklisted = false, punish = false},
    [29] = { name = "Blimp", blacklisted = false, punish = false},
    [30] = { name = "Dir_Flame_Explode", blacklisted = false, punish = false},
    [31] = { name = "Tanker", blacklisted = false, punish = false},
    [32] = { name = "PlaneRocket", blacklisted = true, punish = false},
    [33] = { name = "VehicleBullet", blacklisted = true, punish = false},
    [34] = { name = "Gas_Tank", blacklisted = false, punish = false},
    [35] = { name = "FireWork", blacklisted = true, punish = false},
    [36] = { name = "SnowBall", blacklisted = true, punish = false},
    [37] = { name = "ProxMine", blacklisted = true, punish = false},
    [38] = { name = "Valkyrie_Cannon" , blacklisted = true, punish = true},
	[40] = { name = "Proxmine" , blacklisted = true, punish = true},
    [70] = { name = "AutoMizer", blacklisted = false}

}

Config.BlacklistedPlayerNames = { 
	{name = "Cheat"},
	{name = "https"},	
	{name = "http"},	
	{name = "<"},
	{name = "www."},
	{name = "script"},
	{name = "hack"},
	{name = "src"},
	{name = "administrator"},
	{name = "admin"},
	{name = "adm1n"},
	{name = "adm!n"},
	{name = "admln"},
	{name = "moderator"},
	{name = "owner"},
	{name = "nigger"},
	{name = "n1gger"},
	{name = "moderator"},
	{name = "eulencheats"},
	{name = "lynxmenu"},
	{name = "atgmenu"},
	{name = "hacker"},
	{name = "bastard"},
	{name = "hamhaxia"},
	{name = "333gang"},
	{name = "ukrp"},
	{name = "eguk"},
	{name = "n1gger"},
	{name = "n1ga"},
	{name = "nigga"},
	{name = "n1gga"},
	{name = "nigg3r,"},
	{name = "nig3r"},
	{name = "shagged"},
	{name = "4dm1n"},
	{name = "4dmin"},
	{name = "m0d3r4t0r"},
	{name = "n199er"},
	{name = "n1993r"},
	{name = "rustchance.com"},
	{name = "rustchance"},
	{name = "hellcase.com"},
	{name = "hellcase"},
	{name = "youtube.com"},
	{name = "youtu.be"},
	{name = "youtube"},
	{name = "anticheat"},
	{name = "fucking"},
	{name = "chocohax"},
	{name = "civilgamers.com"},
	{name = "civilgamers"},
	{name = "csgoempire.com"},
	{name = "csgoempire"},
	{name = "g4skins.com"},
	{name = "g4skins"},
	{name = "gameodds.gg"},
	{name = "duckfuck.com"},
	{name = "crysishosting.com"},
	{name = "crysishosting"},
	{name = "key-drop.com"},
	{name = "key-drop.pl"},
	{name = "skinhub.com"},
	{name = "skinhub"},
	{name = "casedrop.eu"},
	{name = "casedrop"},
	{name = "cs.money"},
	{name = "rustypot.com"},
	{name = "☭"},
	{name = "☣"},
	{name = "✠"},
	{name = "dkb.xss.ht"},
	{name = "( . )( . )"},
	{name = "rampage.lt"},
	{name = "xcasecsgo.com"},
	{name = "xcasecsgo"},
	{name = "csgocases.com,"},
	{name = "csgocases"},
	{name = "K9GrillzUK.co.uk"},
	{name = "moat.gg"},
	{name = "princevidz.com"},
	{name = "princevidz"},
	{name = "pvpro.com"},
	{name = "Pvpro"},
	{name = "ez.krimes.ro"},
	{name = "loot.farm"},
	{name = "arma3fisherslife.net"},
	{name = "arma3fisherslife"},
	{name = "egamers.io"},
	{name = "ifn.gg"},
	{name = "key-drop"},
	{name = "sups.gg"},
	{name = "tradeit.gg,"},
	{name = "csgotraders.net"},
	{name = "csgotraders"},
	{name = "hurtfun.com"},
	{name = "hurtfun"},
	{name = "gamekit.com"},
	{name = "t.tv"},
	{name = "yandex.ru"},
	{name = "yandex"},
	{name = "csgofly.com"},
	{name = "csgofly"},
	{name = "pornhub.com"},
	{name = "pornhub"},
	{name = "ᴛᴇᴀᴍ,"},
	{name = "cs.deals,twat"},
	{name = "STRESS.PW"},
	{name = "2g1c"},
	{name = "2 girls 1 cup"},
	{name = "acrotomophilia"},
	{name = "alabama hot pocket"},
	{name = "alaskan pipeline"},
	{name = "anal"},
	{name = "anilingus"},
	{name = "anus"},
	{name = "apeshit"},
	{name = "arsehole"},
	{name = "ass"},
	{name = "asshole"},
	{name = "assmunch"},
	{name = "auto erotic"},
	{name = "autoerotic"},
	{name = "babeland"},
	{name = "baby batter"},
	{name = "baby juice"},
	{name = "ball gag"},
	{name = "ball gravy"},
	{name = "ball kicking"},
	{name = "ball licking"},
	{name = "ball sack"},
	{name = "ball sucking"},
	{name = "bangbros"},
	{name = "bangbus"},
	{name = "bareback"},
	{name = "barely legal"},
	{name = "barenaked"},
	{name = "bastard"},
	{name = "bastardo"},
	{name = "bastinado"},
	{name = "bbw"},
	{name = "bdsm"},
	{name = "beaner"},
	{name = "beaners"},
	{name = "beaver cleaver"},
	{name = "beaver lips"},
	{name = "beastiality"},
	{name = "bestiality"},
	{name = "big black"},
	{name = "big breasts"},
	{name = "big knockers"},
	{name = "big tits"},
	{name = "bimbos"},
	{name = "birdlock"},
	{name = "bitch"},
	{name = "bitches"},
	{name = "black cock"},
	{name = "blonde action"},
	{name = "blonde on blonde action"},
	{name = "blowjob"},
	{name = "blow job"},
	{name = "blow your load"},
	{name = "blue waffle"},
	{name = "blumpkin"},
	{name = "bollocks"},
	{name = "bondage"},
	{name = "boner"},
	{name = "boob"},
	{name = "boobs"},
	{name = "booty call"},
	{name = "brown showers"},
	{name = "brunette action"},
	{name = "bukkake"},
	{name = "bulldyke"},
	{name = "bullet vibe"},
	{name = "bullshit"},
	{name = "bung hole"},
	{name = "bunghole"},
	{name = "busty"},
	{name = "butt"},
	{name = "buttcheeks"},
	{name = "butthole"},
	{name = "camel toe"},
	{name = "camgirl"},
	{name = "camslut"},
	{name = "camwhore"},
	{name = "carpet muncher"},
	{name = "carpetmuncher"},
	{name = "chocolate rosebuds"},
	{name = "cialis"},
	{name = "circlejerk"},
	{name = "cleveland steamer"},
	{name = "clit"},
	{name = "clitoris"},
	{name = "clover clamps"},
	{name = "clusterfuck"},
	{name = "cock"},
	{name = "cocks"},
	{name = "coprolagnia"},
	{name = "coprophilia"},
	{name = "cornhole"},
	{name = "coon"},
	{name = "coons"},
	{name = "creampie"},
	{name = "cum"},
	{name = "cumming"},
	{name = "cumshot"},
	{name = "cumshots"},
	{name = "cunnilingus"},
	{name = "cunt"},
	{name = "darkie"},
	{name = "date rape"},
	{name = "daterape"},
	{name = "deep throat"},
	{name = "deepthroat"},
	{name = "dendrophilia"},
	{name = "dick"},
	{name = "dildo"},
	{name = "dingleberry"},
	{name = "dingleberries"},
	{name = "dirty pillows"},
	{name = "dirty sanchez"},
	{name = "doggie style"},
	{name = "doggiestyle"},
	{name = "doggy style"},
	{name = "doggystyle"},
	{name = "dog style"},
	{name = "dolcett"},
	{name = "domination"},
	{name = "dominatrix"},
	{name = "dommes"},
	{name = "donkey punch"},
	{name = "double dong"},
	{name = "double penetration"},
	{name = "dp action"},
	{name = "dry hump"},
	{name = "dvda"},
	{name = "eat my ass"},
	{name = "ecchi"},
	{name = "ejaculation"},
	{name = "erotic"},
	{name = "erotism"},
	{name = "escort"},
	{name = "eunuch"},
	{name = "fag"},
	{name = "faggot"},
	{name = "fecal"},
	{name = "felch"},
	{name = "fellatio"},
	{name = "feltch"},
	{name = "female squirting"},
	{name = "femdom"},
	{name = "figging"},
	{name = "fingerbang"},
	{name = "fingering"},
	{name = "fisting"},
	{name = "foot fetish"},
	{name = "footjob"},
	{name = "frotting"},
	{name = "fuck"},
	{name = "fuck buttons"},
	{name = "fuckin"},
	{name = "fucking"},
	{name = "fucktards"},
	{name = "fudge packer"},
	{name = "fudgepacker"},
	{name = "futanari"},
	{name = "gangbang"},
	{name = "gang bang"},
	{name = "gay sex"},
	{name = "genitals"},
	{name = "giant cock"},
	{name = "girl on"},
	{name = "girl on top"},
	{name = "girls gone wild"},
	{name = "goatcx"},
	{name = "goatse"},
	{name = "god damn"},
	{name = "gokkun"},
	{name = "golden shower"},
	{name = "goodpoop"},
	{name = "goo girl"},
	{name = "goregasm"},
	{name = "grope"},
	{name = "group sex"},
	{name = "g-spot"},
	{name = "guro"},
	{name = "hand job"},
	{name = "handjob"},
	{name = "hard core"},
	{name = "hardcore"},
	{name = "hentai"},
	{name = "homoerotic"},
	{name = "honkey"},
	{name = "hooker"},
	{name = "horny"},
	{name = "hot carl"},
	{name = "hot chick"},
	{name = "how to kill"},
	{name = "how to murder"},
	{name = "huge fat"},
	{name = "humping"},
	{name = "incest"},
	{name = "intercourse"},
	{name = "jack off"},
	{name = "jail bait"},
	{name = "jailbait"},
	{name = "jelly donut"},
	{name = "jerk"},
	{name = "off"},
	{name = "jigaboo"},
	{name = "jiggaboo"},
	{name = "jiggerboo"},
	{name = "jizz"},
	{name = "juggs"},
	{name = "kike"},
	{name = "kinbaku"},
	{name = "kinkster"},
	{name = "kinky"},
	{name = "knobbing"},
	{name = "leather restraint"},
	{name = "leather straight jacket"},
	{name = "lemon party"},
	{name = "livesex"},
	{name = "lolita"},
	{name = "lovemaking"},
	{name = "make me come"},
	{name = "male squirting"},
	{name = "masturbate"},
	{name = "masturbating"},
	{name = "masturbation"},
	{name = "menage a trois"},
	{name = "milf"},
	{name = "missionary position"},
	{name = "mong"},
	{name = "motherfucker"},
	{name = "mound of venus"},
	{name = "mr hands"},
	{name = "muff diver"},
	{name = "muffdiving"},
	{name = "nambla"},
	{name = "nawashi"},
	{name = "negro"},
	{name = "neonazi"},
	{name = "nigga"},
	{name = "nigger"},
	{name = "nig nog"},
	{name = "nimphomania"},
	{name = "nipple"},
	{name = "nipples"},
	{name = "nsfw"},
	{name = "nsfw images"},
	{name = "nude"},
	{name = "nudity"},
	{name = "nutten"},
	{name = "nympho"},
	{name = "nymphomania"},
	{name = "octopussy"},
	{name = "omorashi"},
	{name = "one cup two girls"},
	{name = "one guy one jar"},
	{name = "orgasm"},
	{name = "orgy"},
	{name = "paedophile"},
	{name = "paki"},
	{name = "panties"},
	{name = "panty"},
	{name = "pedobear"},
	{name = "pedophile"},
	{name = "pegging"},
	{name = "penis"},
	{name = "phone sex"},
	{name = "piece of shit"},
	{name = "pikey"},
	{name = "pissing"},
	{name = "piss pig"},
	{name = "pisspig"},
	{name = "playboy"},
	{name = "pleasure chest"},
	{name = "pole smoker"},
	{name = "ponyplay"},
	{name = "poof"},
	{name = "poon"},
	{name = "poontang"},
	{name = "punany"},
	{name = "poop chute"},
	{name = "poopchute"},
	{name = "porn"},
	{name = "porno"},
	{name = "pornography"},
	{name = "prince albert piercing"},
	{name = "pthc"},
	{name = "pubes"},
	{name = "pussy"},
	{name = "queaf"},
	{name = "queef"},
	{name = "quim"},
	{name = "raghead"},
	{name = "raging boner"},
	{name = "rape"},
	{name = "raping"},
	{name = "rapist"},
	{name = "rectum"},
	{name = "reverse cowgirl"},
	{name = "rimjob"},
	{name = "rimming"},
	{name = "rosy palm"},
	{name = "rosy palm and her 5 sisters"},
	{name = "rusty trombone"},
	{name = "sadism"},
	{name = "santorum"},
	{name = "scat"},
	{name = "schlong"},
	{name = "scissoring"},
	{name = "semen"},
	{name = "sex"},
	{name = "sexcam"},
	{name = "sexo"},
	{name = "sexy"},
	{name = "sexual"},
	{name = "sexually"},
	{name = "sexuality"},
	{name = "shaved beaver"},
	{name = "shaved pussy"},
	{name = "shemale"},
	{name = "shibari"},
	{name = "shit"},
	{name = "shitblimp"},
	{name = "shitty"},
	{name = "shota"},
	{name = "shrimping"},
	{name = "skeet"},
	{name = "slanteye"},
	{name = "slut"},
	{name = "s&m"},
	{name = "smut"},
	{name = "snatch"},
	{name = "snowballing"},
	{name = "sodomize"},
	{name = "sodomy"},
	{name = "spastic"},
	{name = "spic"},
	{name = "splooge"},
	{name = "splooge moose"},
	{name = "spooge"},
	{name = "spread legs"},
	{name = "spunk"},
	{name = "strap on"},
	{name = "strapon"},
	{name = "strappado"},
	{name = "strip club"},
	{name = "style doggy"},
	{name = "suck"},
	{name = "sucks"},
	{name = "suicide girls"},
	{name = "sultry women"},
	{name = "swastika"},
	{name = "swinger"},
	{name = "tainted love"},
	{name = "taste my"},
	{name = "tea bagging"},
	{name = "threesome"},
	{name = "throating"},
	{name = "thumbzilla"},
	{name = "tied up"},
	{name = "tight white"},
	{name = "tit"},
	{name = "tits"},
	{name = "titties"},
	{name = "titty"},
	{name = "tongue in a"},
	{name = "topless"},
	{name = "tosser"},
	{name = "towelhead"},
	{name = "tranny"},
	{name = "tribadism"},
	{name = "tub girl"},
	{name = "tubgirl"},
	{name = "tushy"},
	{name = "twat"},
	{name = "twink"},
	{name = "twinkie"},
	{name = "two girls one cup"},
	{name = "undressing"},
	{name = "upskirt"},
	{name = "urethra play"},
	{name = "urophilia"},
	{name = "vagina"},
	{name = "venus mound"},
	{name = "viagra"},
	{name = "vibrator"},
	{name = "violet wand"},
	{name = "vorarephilia"},
	{name = "voyeur"},
	{name = "voyeurweb"},
	{name = "voyuer"},
	{name = "vulva"},
	{name = "wank"},
	{name = "wetback"},
	{name = "wet dream"},
	{name = "white power"},
	{name = "whore"},
	{name = "worldsex"},
	{name = "wrapping men"},
	{name = "wrinkled starfish"},
	{name = "xx"},
	{name = "xxx"},
	{name = "yaoi"},
	{name = "yellow showers"},
	{name = "yiffy"},
	{name = "zoophilia"},
	{name = "abbo"},
	{name = "abo"},
	{name = "beeyotch"},
	{name = "biatch"},
	{name = "bitch"},
	{name = "chinaman"},
	{name = "chinamen"},
	{name = "chink"},
	{name = "coolie"},
	{name = "coon"},
	{name = "crazie"},
	{name = "crazy"},
	{name = "crip"},
	{name = "cuck"},
	{name = "cunt"},
	{name = "dago"},
	{name = "daygo"},
	{name = "dego"},
	{name = "dick"},
	{name = "douchebag"},
	{name = "dumb"},
	{name = "dyke"},
	{name = "eskimo"},
	{name = "fag"},
	{name = "faggot"},
	{name = "fatass"},
	{name = "fatso"},
	{name = "gash"},
	{name = "gimp"},
	{name = "golliwog"},
	{name = "gook"},
	{name = "goy"},
	{name = "goyim"},
	{name = "gyp"},
	{name = "gypsy"},
	{name = "half-breed"},
	{name = "halfbreed"},
	{name = "heeb"},
	{name = "homo"},
	{name = "hooker"},
	{name = "idiot"},
	{name = "insane"},
	{name = "insanitie"},
	{name = "insanity"},
	{name = "jap"},
	{name = "kaffer"},
	{name = "kaffir"},
	{name = "kaffir"},
	{name = "kaffre"},
	{name = "kafir"},
	{name = "kike"},
	{name = "kraut"},
	{name = "lame"},
	{name = "lardass"},
	{name = "lesbo"},
	{name = "lunatic"},
	{name = "mick"},
	{name = "negress"},
	{name = "negro"},
	{name = "nig"},
	{name = "nig-nog"},
	{name = "nigga"},
	{name = "nigger"},
	{name = "nigguh"},
	{name = "nip"},
	{name = "pajeet"},
	{name = "paki"},
	{name = "pickaninnie"},
	{name = "pickaninny"},
	{name = "prostitute"},
	{name = "pussie"},
	{name = "pussy"},
	{name = "raghead"},
	{name = "retard"},
	{name = "sambo"},
	{name = "shemale"},
	{name = "skank"},
	{name = "slut"},
	{name = "soyboy"},
	{name = "spade"},
	{name = "sperg"},
	{name = "spic"},
	{name = "spook"},
	{name = "squaw"},
	{name = "street-shitter"},
	{name = "tard"},
	{name = "tits"},
	{name = "titt"},
	{name = "trannie"},
	{name = "tranny"},
	{name = "twat"},
	{name = "wetback"},
	{name = "whore"},
	{name = "wigger"},
	{name = "wop"},
	{name = "yid"},
	{name = "zog"}
}

Config.BlacklistedMessages = {
    "Bombay Menu",
    "Brutan Premium",
    "d0pamine | Nertigel#5391",
    "3You just got fucked by Luminous ^2Made by Plane#0007 ^1Purchase at ^4https://discord.gg/pQwzbdf",
    "Yo add me Fallen#0811",
    "d0pamine.xyz | discord.gg/fjBp55t",
    "Add me Baby Gangster#9026",
    "Yo add me Baby Gangster#9026",
    "EulenCheats",
    "Anti-Lynx",
    "Lynx 8",
    "Lynx 7",
    "lynxmenu",
    "HamHaxia",
    "Ham Mafia",
    "hammafia.com",
    "www.renalua.com",
    "Fallen#0811",
    ">:D Player Crash",  
    "34ByTe Community",
    "MARVIN menu",
    "BAGGY menu <3 https://discord.gg/AGxGDzg",
    "KoGuSzMENU <3 https://discord.gg/BbDMhJe",
    "Desudo menu <3 https://discord.gg/hkZgrv3",
    "You got raped by AlphaV",
    "TITO MODZ",
	'Desudo',
	'Brutan',
	'EulenCheats',
	"www.lynxmenu.com",
	"Ham Mafia",
	"Rena 8",
	"Xanax#0134",
	"lynxmenu.com",
	"Baran#8992",
	"iLostName#7138",
	"85.190.90.118",
	"AlphaV ~ 5391",
	"vjuton.pl",
	"EulenCheat",
	"Eulen",
	"Lynx",
	"lynxmenu.com - Cheats & Anti-Cheats!",
	"Soviet Bear",	
	"CK GANG",		
	"CK GANG!",
	"CK MAFIE",	
	"desudo",	
	"RedEngine",	
	"FiveMock",	
	"dopamine",	
	"Kubca",	
	"jsem cheater",	
	"cheatuju",	
	"NEGR",	
	"nigga",	
	"fortnitegang",	
	"ck bratva",	
	"ck terror",
	"CK BLOODS",
	"TAJNEMENUMenu",	
	"https://dc.xaries.pl",	
	"xaries.pl",	
	"SKAZA",	
	"SKAZA V500",	
	"xaries",	
	"xariesgang2",	
	"xariesgang3",	
	"xariesv2",	
	"xariesgang3",	
	"xaries gang 3*",	
	"ariesv1.0_1_1",	
	"BEE_1",	
	"renalua",	
	"Fallen",	
	"Xanax",	
	"MainMenu",	
	"SelfMenu",	
	"Baran",
	"iLostName",
	"LynX",
	"LynxX",
	"stt_prop_stunt_soccer_ball",
	"WarMenu",
	"INTERACTION MENU",
	"ARIES MENU",
	"XARIES",
	"666 GANG",
	"6666",
	"85.190.90.118",
	"Melon#1379",
	"hammafia.com",
	"TITOMODZ",
	"xseira",
	"AlphaV",
	"Soviet",
	"fefev",
	"ariesMenu",
	"AlikhanCheats",
	"FUCKFIVEMDOWNLOADHACKS",
	"DOWNLOADHACK",
	"fuckfivemdownloadhacks",
	"downloadhack",
	"werfvtghiouuiowrfetwerfio",
	"Lynx8",
	"LynxSeven",
	"KoGuSzEk",
	"lynxunknowncheats",
	"unknowncheats",
	"cheats",
	"cheat",
	"hack",
	"hacks",
	"BrutanPremium",
	"gaybuild",
	"TiagoMenu",
	"Dopamine",
	"MMenu",
	"nigmenu0001",
	"HamMafia",
	"b00mek",
	"LynxEvo",
    "SKAZAMENU",
}

Config.BlackListedObjects = {}

Config.BlackListedPeds = {}

Config.BlackListedPedsSpawn = {
	{name = "s_m_y_swat_01", punish = false},
	{name = "u_m_y_juggernaut_01", punish = true},
	{name = "s_m_m_movalien_01", punish = true},
	{name = "a_m_y_acult_02", punish = true},
	{name = "a_m_o_acult_02", punish = true},
	{name = "a_m_m_acult_02", punish = true},
	{name = "u_m_m_streetart_01", punish = true},
	{name = "u_m_y_rsranger_01", punish = true},
	{name = "u_m_y_pogo_01", punish = true},
	{name = "ig_orleans", punish = true},
	{name = "cs_orleans", punish = true},
	{name = "mp_m_niko_01", punish = true},
	{name = "s_m_m_movspace_01", punish = true},
	{name = "mp_m_marston_01", punish = true},
	{name = "ig_johnnyklebitz", punish = true},
	{name = "a_c_chimp", punish = true},
	{name = "cs_bradcadaver", punish = true},
	{name = "u_m_y_zombie_01", punish = true},
	{name = "a_m_o_acult_01", punish = true},
	{name = "a_m_m_acult_01", punish = true},
	{name = "a_m_y_acult_01", punish = true},
	{name = "ig_wade", punish = true},
	{name = "s_m_m_paramedic_01", punish = false},
	{name = "s_m_y_fireman_01", punish = true},
	{name = "a_m_y_mexthug_01", punish = true},
}

Config.BlacklistedWeapons = {}
Config.BlackListedVehicles = {}

Config.BlackListedServerEvents = {}

Config.WhitelistedObjects = {}

Config.WhitelistedVehicles = {}

Config.WhitelistedPeds = {
	"mp_f_freemode_01",
	"mp_m_freemode_01",
	"a_m_y_hipster_02",
	"a_m_m_skater_01",
	"a_m_y_skater_01",
	"a_m_y_skater_02"
}